# Generated by Django 4.2.9 on 2026-01-11 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_confirmed_at_booking_expires_at_and_more'),
        ('payments', '0002_wallet_wallettransaction_cashbackledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, help_text='Link to original debit transaction if this is a refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='payments.wallettransaction'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('refund', 'Refund')], max_length=20),
        ),
    ]
