# Generated by Django 4.2.9 on 2026-01-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_wallettransaction_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='cashback_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
