# Generated by Django 4.2.9 on 2026-01-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_wallet_cashback_earned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='reference_id',
            new_name='gateway_order_id',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='parent_transaction',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_gateway',
            field=models.CharField(choices=[('cashfree', 'Cashfree'), ('razorpay', 'Razorpay'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('internal', 'Internal')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('cashback', 'Cashback'), ('refund', 'Refund')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='payments_wa_wallet__fd9a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status'], name='payments_wa_status_f053a4_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['gateway_order_id'], name='payments_wa_gateway_02faa5_idx'),
        ),
    ]
