# Generated by Django 4.2.9 on 2026-01-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_wallettransaction_balance_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
