# Generated by Django 4.2.9 on 2026-01-16 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_bonus_transaction_type'),
        ('payments', '0006_alter_wallettransaction_balance_after_and_more'),
    ]

    operations = [
    ]
