# Generated by Django 4.2.9 on 2026-01-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_merge_20260116_0717'),
        ('payments', '0007_wallettransaction_reference_id'),
    ]

    operations = [
    ]
