# Generated by Django 4.2.9 on 2026-01-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_merge_20260116_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
