# Generated by Django 4.2.9 on 2026-01-16 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_merge_20260116_0825'),
        ('payments', '0008_wallettransaction_reference_id'),
    ]

    operations = [
    ]
