# Generated by Django 4.2.9 on 2026-01-11 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.CharField(choices=[('email', 'Email OTP'), ('mobile', 'Mobile OTP')], max_length=10)),
                ('otp_code', models.CharField(max_length=6)),
                ('contact', models.CharField(help_text='Email or phone number where OTP was sent', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User OTP',
                'verbose_name_plural': 'User OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'otp_type', '-created_at'], name='users_usero_user_id_330ed5_idx'), models.Index(fields=['contact', 'otp_type'], name='users_usero_contact_e0240c_idx')],
            },
        ),
    ]
