# Generated by Django 4.2.9 on 2026-01-13 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified_at_user_phone_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userotp',
            name='users_usero_contact_e0240c_idx',
        ),
        migrations.AddField(
            model_name='userotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('verification', 'General Verification')], default='registration', help_text='Purpose of OTP (registration, password_reset, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User instance if linked; None for pre-registration phone-based OTP', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userotp',
            index=models.Index(fields=['contact', 'otp_type', 'purpose'], name='users_usero_contact_561417_idx'),
        ),
    ]
