# Generated by Django 4.2.9 on 2026-01-13 17:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0007_booking_confirmed_at_booking_expires_at_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(help_text='Company name (e.g., Tata Consultancy Services)', max_length=200)),
                ('email_domain', models.CharField(db_index=True, help_text='Email domain (e.g., tcs.com, infosys.com)', max_length=100, unique=True)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat Discount'), ('percentage', 'Percentage Discount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('applicable_to', models.CharField(choices=[('all', 'All Services'), ('hotel', 'Hotels Only'), ('bus', 'Buses Only'), ('package', 'Packages Only')], default='all', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='ONE-CLICK TOGGLE: Enable/disable corporate discount instantly')),
            ],
            options={
                'verbose_name': 'Corporate Discount',
                'verbose_name_plural': 'Corporate Discounts',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Promo code (e.g., SUMMER2026, WELCOME50)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal description for admin reference')),
                ('discount_type', models.CharField(choices=[('flat', 'Flat Discount'), ('percentage', 'Percentage Discount')], default='percentage', help_text='Type of discount to apply', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount amount (₹ for flat, % for percentage)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_booking_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum booking amount required to use this code', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('applicable_to', models.CharField(choices=[('all', 'All Services'), ('hotel', 'Hotels Only'), ('bus', 'Buses Only'), ('package', 'Packages Only')], default='all', help_text='Which services this promo code applies to', max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Promo code becomes active from this date')),
                ('valid_until', models.DateTimeField(help_text='Promo code expires after this date')),
                ('max_total_uses', models.PositiveIntegerField(blank=True, help_text='Maximum total uses across all users (leave blank for unlimited)', null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Maximum uses per user')),
                ('total_uses', models.PositiveIntegerField(default=0, help_text='Current total uses (auto-incremented)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='ONE-CLICK TOGGLE: Enable/disable this promo code instantly')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual discount applied', max_digits=10)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to='bookings.booking')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='core.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code', 'is_active'], name='core_promoc_code_8d2fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['valid_from', 'valid_until'], name='core_promoc_valid_f_591cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['user', 'promo_code'], name='core_promoc_user_id_305e0a_idx'),
        ),
    ]
