# Generated by Django 4.2.9 on 2026-01-15 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_corporatediscount_promocode_promocodeusage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(help_text='Official company name', max_length=200)),
                ('email_domain', models.CharField(db_index=True, help_text='Official email domain (e.g., company.com) - users with this domain auto-linked', max_length=100, unique=True)),
                ('gst_number', models.CharField(blank=True, help_text='GST number (optional now, required for approval)', max_length=20)),
                ('account_type', models.CharField(choices=[('business', 'Business'), ('enterprise', 'Enterprise'), ('startup', 'Startup'), ('government', 'Government')], default='business', max_length=20)),
                ('contact_person_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_verification', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_corporate_accounts', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_corporate_accounts', to=settings.AUTH_USER_MODEL)),
                ('corporate_coupon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_corporate_account', to='core.promocode')),
            ],
            options={
                'verbose_name': 'Corporate Account',
                'verbose_name_plural': 'Corporate Accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_domain', 'status'], name='core_corpor_email_d_614c9d_idx'), models.Index(fields=['status', 'is_active'], name='core_corpor_status_e7efad_idx')],
            },
        ),
    ]
