# Generated by Django 4.2.9 on 2026-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpayout',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='bank_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='block_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='can_payout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='penalties',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='refunds_issued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerpayout',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ownerpayout',
            name='gross_booking_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ownerpayout',
            name='net_payable_to_owner',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ownerpayout',
            name='settlement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('kyc_pending', 'KYC Pending'), ('bank_pending', 'Bank Details Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20),
        ),
    ]
