# Generated by ChatGPT for adding itinerary_text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_deleted_at_package_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='itinerary_text',
            field=models.TextField(blank=True, help_text='Single-field itinerary/notes for quick edits'),
        ),
    ]
