# Generated by Django 4.2.9 on 2026-01-06 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_pricelog_hoteldiscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="channel_manager_name",
            field=models.CharField(
                blank=True,
                help_text="Optional external channel manager provider name",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="inventory_source",
            field=models.CharField(
                choices=[
                    ("external_cm", "External Channel Manager"),
                    ("internal_cm", "Internal (GoExplorer)"),
                ],
                default="internal_cm",
                help_text="Defines whether this property is managed by an external channel manager or GoExplorer internal inventory",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ChannelManagerRoomMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("generic", "Generic"),
                            ("staah", "STAAH"),
                            ("ratehawk", "RateHawk"),
                            ("djubo", "Djubo"),
                            ("other", "Other"),
                        ],
                        default="generic",
                        max_length=50,
                    ),
                ),
                ("external_room_id", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_mappings",
                        to="hotels.hotel",
                    ),
                ),
                (
                    "room_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_mapping",
                        to="hotels.roomtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel Manager Mapping",
                "verbose_name_plural": "Channel Manager Mappings",
                "ordering": ["hotel__name", "room_type__name"],
            },
        ),
    ]
