# Generated by Django 4.2.9 on 2026-01-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_channel_manager_name_hotel_inventory_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='property_rules',
            field=models.TextField(blank=True, help_text='House rules, check-in policies, ID requirements'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('villa', 'Villa'), ('homestay', 'Homestay'), ('lodge', 'Lodge / Residency / Cottage')], default='hotel', help_text='Property category (hotel/resort/villa/homestay/lodge)', max_length=20),
        ),
    ]
