# Generated by Django 4.2.9 on 2026-01-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_property_rules_hotel_property_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelimage',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers first)'),
        ),
    ]
