# Generated by Django 4.2.9 on 2026-01-13 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0006_add_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - if True, record is logically deleted'),
        ),
    ]
