# Generated by Django 4.2.9 on 2026-01-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotel_deleted_at_hotel_deleted_by_hotel_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='Cancellation and refund policy'),
        ),
    ]
