# Generated by ChatGPT for adding amenities_rules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotel_cancellation_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities_rules',
            field=models.TextField(blank=True, help_text='Amenity details and usage rules shown as a paragraph'),
        ),
    ]
