# Generated by Django 4.2.9 on 2026-01-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_add_cancellation_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.CharField(choices=[('room_only', 'Room Only'), ('room_breakfast', 'Room + Breakfast'), ('room_half_board', 'Room + Breakfast + Dinner'), ('room_full_board', 'Room + All Meals')], max_length=20)),
                ('name', models.CharField(help_text='Display name for this meal plan', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Total price per night including room and meals (absolute pricing)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='hotels.roomtype')),
            ],
            options={
                'ordering': ['room_type', 'display_order', 'id'],
                'unique_together': {('room_type', 'plan_type')},
            },
        ),
    ]
