# Generated by Django 4.2.9 on 2026-01-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_add_room_type_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommealplan',
            name='plan_type',
            field=models.CharField(choices=[('room_only', 'Room Only'), ('room_breakfast', 'Room + Breakfast'), ('room_half_board', 'Room + Breakfast + Lunch/Dinner'), ('room_full_board', 'Room + All Meals')], max_length=20),
        ),
    ]
