# Generated by Django 4.2.9 on 2026-01-21 05:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_add_role_based_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='discount_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', help_text='Room-level discount type (mutually exclusive).', max_length=20),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='discount_valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='discount_valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount value based on discount_type.', max_digits=10),
        ),
    ]
