# Generated by Django 4.2.9 on 2026-01-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_roomcancellationpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcancellationpolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
