# Generated by Django 4.2.9 on 2026-01-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_alter_roomcancellationpolicy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft - Being configured'), ('READY', 'Ready - All fields complete'), ('APPROVED', 'Approved - Admin verified')], default='DRAFT', help_text='DRAFT: in progress, READY: awaiting approval', max_length=20),
        ),
    ]
