# Generated by Django 4.2.9 on 2026-01-23 07:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_roomtype_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Breakfast Included')", max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('room_only', 'Room Only'), ('breakfast', 'Breakfast Included'), ('half_board', 'Half Board (Breakfast + Lunch/Dinner)'), ('full_board', 'Full Board (All Meals)'), ('all_inclusive', 'All Inclusive')], max_length=20, unique=True)),
                ('inclusions', models.JSONField(blank=True, default=list, help_text="List of included items (e.g., ['Breakfast', 'Wi-Fi'])")),
                ('description', models.TextField(blank=True, help_text="What's included in this meal plan")),
                ('is_refundable', models.BooleanField(default=True, help_text='Can bookings with this meal plan be refunded?')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'ID Proof Required')", max_length=100)),
                ('category_type', models.CharField(choices=[('must_read', 'Must Read'), ('guest_profile', 'Guest Profile'), ('id_proof', 'ID Proof Required'), ('smoking', 'Smoking & Alcohol'), ('food', 'Food & Beverage'), ('pets', 'Pet Policy'), ('cancellation', 'Cancellation Policy'), ('checkin_checkout', 'Check-in & Check-out'), ('other', 'Other')], max_length=20, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='CSS icon class (optional)', max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first in guest UI')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Policy Categories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='roommealplan',
            options={'ordering': ['room_type', 'display_order', 'meal_plan__display_order', 'id']},
        ),
        migrations.AddField(
            model_name='roommealplan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-select this meal plan for this room?'),
        ),
        migrations.AddField(
            model_name='roommealplan',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional cost per night for this meal plan (can be 0 for Room Only)', max_digits=10),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed'), ('twin', 'Twin Beds'), ('bunk', 'Bunk Bed')], help_text='Bed type (e.g., King, Twin)', max_length=20),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_refundable',
            field=models.BooleanField(default=True, help_text='Can bookings for this room be refunded/cancelled?'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='max_adults',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of adults allowed', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='max_children',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of children allowed (can be 0)'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_occupancy',
            field=models.IntegerField(default=2, help_text='Total max guests (auto-calculated from adults + children)'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_size',
            field=models.IntegerField(blank=True, help_text='Size in square feet (sqft) - MANDATORY for approval', null=True),
        ),
        migrations.CreateModel(
            name='PropertyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Policy statement (e.g., 'Pets are not allowed')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional details (optional)')),
                ('is_highlighted', models.BooleanField(default=False, help_text="Show in 'Must Read' section at top")),
                ('display_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_policies', to='hotels.policycategory')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='hotels.hotel')),
            ],
            options={
                'verbose_name_plural': 'Property Policies',
                'ordering': ['category__display_order', 'display_order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='roommealplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roommealplan',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_meal_plans', to='hotels.mealplan'),
        ),
        migrations.AlterUniqueTogether(
            name='roommealplan',
            unique_together={('room_type', 'meal_plan')},
        ),
        migrations.RemoveField(
            model_name='roommealplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roommealplan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='roommealplan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='roommealplan',
            name='price_per_night',
        ),
    ]
