# Generated by Django 4.2.9 on 2026-01-23 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0019_mealplan_policycategory_alter_roommealplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_from', models.DateField(help_text='Start date (inclusive)')),
                ('blocked_to', models.DateField(help_text='End date (inclusive)')),
                ('reason', models.CharField(blank=True, help_text="Optional reason for blocking (e.g., 'Maintenance', 'Owner use')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Active blocks prevent bookings')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hotels.roomtype')),
            ],
            options={
                'ordering': ['blocked_from', 'blocked_to'],
                'indexes': [models.Index(fields=['room_type', 'blocked_from', 'blocked_to'], name='hotels_room_room_ty_555da0_idx'), models.Index(fields=['is_active'], name='hotels_room_is_acti_dc3c63_idx')],
            },
        ),
    ]
