# Generated by Django 4.2.9 on 2026-01-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_add_roomblock_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hourly_stays_enabled',
            field=models.BooleanField(default=False, help_text='Enable hourly stay booking flow (6h/12h/24h)'),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='category',
            field=models.CharField(choices=[('property', 'Property Photos'), ('room', 'Room Photos'), ('traveller', 'Traveller Photos')], default='property', help_text='Categorize images for gallery sections', max_length=20),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hourly_price_12h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for 12-hour stay', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hourly_price_24h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for 24-hour stay', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hourly_price_6h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for 6-hour stay', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='supports_hourly',
            field=models.BooleanField(default=False, help_text='Allow hourly booking for this room type'),
        ),
    ]
