# Generated by Django 4.2.9 on 2026-01-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_owners', '0009_propertyroomtype_meal_plans'),
        ('hotels', '0021_hotel_hourly_stays_enabled_hotelimage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='owner_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel', to='property_owners.property'),
        ),
    ]
