# Generated by Django 4.2.9 on 2026-01-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_seatlayout_reserved_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='buses/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('display_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_primary', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buses.bus')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
