# Generated by Django 4.2.9 on 2026-01-18 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_corporateaccount'),
        ('buses', '0005_busoperator_deleted_at_busoperator_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busoperator',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft (Incomplete)'), ('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Operator approval state', max_length=20),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When admin approved', null=True),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bus_operators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='base_fare_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average base fare per seat', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='bus_type',
            field=models.CharField(blank=True, choices=[('ac_seater', 'AC Seater'), ('non_ac_seater', 'Non-AC Seater'), ('sleeper', 'Sleeper'), ('semi_sleeper', 'Semi-Sleeper')], help_text='Primary bus type operated', max_length=50),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='cancellation_cutoff_hours',
            field=models.IntegerField(blank=True, help_text='Hours before departure for cancellation', null=True),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='Detailed cancellation policy'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='company_legal_name',
            field=models.CharField(blank=True, help_text='Legal company name (e.g., ABC Tours Pvt Ltd)', max_length=200),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='fleet_size',
            field=models.IntegerField(blank=True, help_text='Total number of buses', null=True),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='gst_percentage',
            field=models.IntegerField(default=5, help_text='GST percentage'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='has_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='has_blanket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='has_charging_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='has_water_bottle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='operator_office_address',
            field=models.TextField(blank=True, help_text='Full office address'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='primary_destination_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators_to', to='core.city'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='primary_source_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators_from', to='core.city'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='refund_percentage',
            field=models.IntegerField(default=100, help_text='Refund percentage on cancellation'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (visible to operator)'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='routes_description',
            field=models.TextField(blank=True, help_text='Describe your routes, stops, and schedule'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When operator submitted for approval', null=True),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='total_seats_per_bus',
            field=models.IntegerField(blank=True, help_text='Seats per bus', null=True),
        ),
        migrations.AddIndex(
            model_name='busoperator',
            index=models.Index(fields=['approval_status', 'is_active'], name='buses_busop_approva_e40100_idx'),
        ),
        migrations.AddIndex(
            model_name='busoperator',
            index=models.Index(fields=['user', 'approval_status'], name='buses_busop_user_id_5af099_idx'),
        ),
    ]
