# Generated by Django 4.2.9 on 2026-01-23 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buses', '0006_session3_operator_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusScheduleImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='buses/schedule_imports/')),
                ('status', models.CharField(choices=[('pending', 'Pending Validation'), ('validated', 'Validated - Ready to Import'), ('importing', 'Importing...'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_schedules', models.IntegerField(default=0)),
                ('skipped_schedules', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_imports', to='buses.busoperator')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_imports_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
