# Generated by Django 4.2.9 on 2026-01-11 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0004_busimage'),
        ('packages', '0002_add_image_fields'),
        ('hotels', '0006_add_image_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('hotel', 'Hotel Review'), ('bus', 'Bus Review'), ('package', 'Package Review')], max_length=20)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved reviews are visible on frontend')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide without deleting')),
                ('booking_id', models.CharField(blank=True, help_text='Link to booking for verification', max_length=100)),
                ('helpful_count', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_reviews_approved', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package Review',
                'verbose_name_plural': 'Package Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('hotel', 'Hotel Review'), ('bus', 'Bus Review'), ('package', 'Package Review')], max_length=20)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved reviews are visible on frontend')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide without deleting')),
                ('booking_id', models.CharField(blank=True, help_text='Link to booking for verification', max_length=100)),
                ('helpful_count', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_reviews_approved', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel Review',
                'verbose_name_plural': 'Hotel Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('hotel', 'Hotel Review'), ('bus', 'Bus Review'), ('package', 'Package Review')], max_length=20)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved reviews are visible on frontend')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide without deleting')),
                ('booking_id', models.CharField(blank=True, help_text='Link to booking for verification', max_length=100)),
                ('helpful_count', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_reviews_approved', to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='buses.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bus Review',
                'verbose_name_plural': 'Bus Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
