# Generated by Django 4.2.9 on 2026-01-12 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_confirmed_at_booking_expires_at_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busreview',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='hotelreview',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='packagereview',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='busreview',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Link to booking for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Link to booking for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='packagereview',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Link to booking for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking'),
        ),
    ]
