# Generated by Django 4.2.9 on 2026-01-18 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_corporateaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_owners', '0002_propertyamenity_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal admin notes (not visible to owner)'),
        ),
        migrations.AddField(
            model_name='property',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft (Incomplete)'), ('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Draft → Pending → Approved/Rejected', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='cancellation_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cancellation_type',
            field=models.CharField(blank=True, choices=[('no_cancellation', 'No Cancellation'), ('until_checkin', 'Free cancellation until check-in'), ('x_days_before', 'Free cancellation X days before check-in')], max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='checkin_time',
            field=models.TimeField(blank=True, help_text='e.g., 14:00', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='checkout_time',
            field=models.TimeField(blank=True, help_text='e.g., 11:00', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.city'),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='gst_percentage',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='property',
            name='has_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_spa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_rules',
            field=models.TextField(blank=True, help_text='Check-in/out policies, pets, smoking, etc.'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_owners.propertytype'),
        ),
        migrations.AddField(
            model_name='property',
            name='refund_percentage',
            field=models.IntegerField(default=100, help_text='Refund percentage'),
        ),
        migrations.AddField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (visible to owner)'),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When owner submitted for verification', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='Additional amenities (free text)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per night', max_digits=10, null=True),
        ),
    ]
