# Generated by Django 4.2.9 on 2026-01-19 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_add_role_based_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_owners', '0003_property_address_property_admin_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_type', models.CharField(choices=[('property_owner', 'Property Owner Verification'), ('update_request', 'Update Request'), ('image', 'Image Upload'), ('pricing', 'Pricing Change')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('room_types', 'Room Types'), ('pricing', 'Pricing'), ('images', 'Images'), ('amenities', 'Amenities'), ('rules', 'Rules')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('occupancy_threshold', models.IntegerField(default=70, help_text='Min occupancy % to apply discount')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Platform Admin'), ('property_owner', 'Property Owner'), ('operator', 'Bus Operator'), ('corporate', 'Corporate Partner'), ('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['approval_status', 'is_active'], name='property_ow_approva_89f789_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'approval_status'], name='property_ow_owner_i_6c858d_idx'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seasonalpricing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_owners.propertyowner'),
        ),
        migrations.AddField(
            model_name='seasonalpricing',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_pricing', to='hotels.roomtype'),
        ),
        migrations.AddField(
            model_name='propertyupdaterequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='property_owners.propertyowner'),
        ),
        migrations.AddField(
            model_name='propertyupdaterequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_property_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminapprovallog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
