# Generated by Django 4.2.9 on 2026-01-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_owners', '0004_add_role_based_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Room type name (e.g., Deluxe Ocean View)', max_length=100)),
                ('room_type', models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('family', 'Family Room'), ('dormitory', 'Dormitory')], default='standard', max_length=20)),
                ('description', models.TextField(help_text='Room description, features, view details')),
                ('max_occupancy', models.PositiveIntegerField(default=2)),
                ('number_of_beds', models.PositiveIntegerField(default=1)),
                ('room_size', models.PositiveIntegerField(blank=True, help_text='Size in square feet', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per night', max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price', max_digits=10, null=True)),
                ('total_rooms', models.PositiveIntegerField(help_text='Total number of this room type available')),
                ('amenities', models.JSONField(default=list, help_text='Room-specific amenities (balcony, TV, minibar, safe, etc.)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_rooms/')),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='property_owners.property')),
            ],
            options={
                'verbose_name': 'Property Room Type',
                'verbose_name_plural': 'Property Room Types',
                'ordering': ['property', 'base_price'],
            },
        ),
    ]
