# Generated by Django 4.2.9 on 2026-01-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_owners', '0005_propertyroomtype'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='property_ow_approva_89f789_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='property_ow_owner_i_6c858d_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', help_text='DRAFT → PENDING → APPROVED/REJECTED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'is_active'], name='property_ow_status_8f6f82_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'status'], name='property_ow_owner_i_c0d40d_idx'),
        ),
    ]
