# Generated by Django 4.2.9 on 2026-01-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_owners', '0006_remove_property_property_ow_approva_89f789_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (visible to owner)', null=True),
        ),
    ]
