# Generated by Django 4.2.9 on 2026-01-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_owners', '0007_alter_property_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyroomtype',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='propertyroomtype',
            name='discount_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyroomtype',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', help_text='Choose either percentage or flat discount (mutually exclusive).', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyroomtype',
            name='discount_valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyroomtype',
            name='discount_valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyroomtype',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount value based on discount type.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='propertyroomtype',
            name='image',
            field=models.ImageField(blank=True, help_text='Legacy primary image', null=True, upload_to='property_rooms/'),
        ),
        migrations.CreateModel(
            name='PropertyRoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='property_rooms/gallery/')),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property_owners.propertyroomtype')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order', 'id'],
            },
        ),
    ]
