# Generated by Django 4.2.9 on 2026-01-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_owners', '0008_remove_propertyroomtype_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyroomtype',
            name='meal_plans',
            field=models.JSONField(default=list, help_text='List of meal plans with absolute per-night pricing for this room'),
        ),
    ]
