# Generated by Django 4.2.9 on 2026-01-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_owners', '0002_property_approval_workflow'),
        ('property_owners', '0009_propertyroomtype_meal_plans'),
    ]

    operations = [
    ]
