# Generated by Django 4.2.9 on 2026-01-25 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_owners', '0010_merge_20260125_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('pricing', 'Pricing'), ('images', 'Images'), ('amenities', 'Amenities'), ('meal_plans', 'Meal Plans')], max_length=50)),
                ('owner_remark', models.TextField(blank=True)),
                ('admin_remark', models.TextField(blank=True)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='propertyapprovalrequest',
            new_name='property_ow_propert_81f97b_idx',
            old_name='property_ow_propert_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyapprovalrequest',
            new_name='property_ow_status_a6d47d_idx',
            old_name='property_ow_status_idx',
        ),
        migrations.AddField(
            model_name='propertyupdaterequest',
            name='admin_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertyupdaterequest',
            name='owner_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propertyupdaterequest',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='property_owners.property'),
        ),
        migrations.AddField(
            model_name='propertyupdaterequest',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_update_requests', to='property_owners.propertyroomtype'),
        ),
        migrations.AlterField(
            model_name='propertyapprovalauditlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_approval_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyapprovalchecklist',
            name='items',
            field=models.JSONField(default=dict, help_text="Dict mapping CHECKLIST_ITEMS to {status: PASS/FAIL/PENDING, notes: ''}"),
        ),
        migrations.AlterField(
            model_name='propertyapprovalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyapprovalrequest',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_revocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyapprovalrequest',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyupdaterequest',
            name='change_type',
            field=models.CharField(choices=[('room_types', 'Room Types'), ('pricing', 'Pricing'), ('images', 'Images'), ('amenities', 'Amenities'), ('rules', 'Rules'), ('meal_plans', 'Meal Plans'), ('discount', 'Property Discount')], max_length=50),
        ),
        migrations.AddField(
            model_name='roomupdaterequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_update_requests', to='property_owners.propertyowner'),
        ),
        migrations.AddField(
            model_name='roomupdaterequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_room_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomupdaterequest',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates', to='property_owners.propertyroomtype'),
        ),
    ]
