# Generated by Django 4.2.9 on 2026-01-06 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0004_hotel_channel_manager_name_hotel_inventory_source_and_more"),
        ("bookings", "0004_add_channel_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cm_booking_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="booking",
            name="inventory_channel",
            field=models.CharField(
                choices=[
                    ("internal_cm", "Internal CM"),
                    ("external_cm", "External CM"),
                ],
                default="internal_cm",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="lock_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name="InventoryLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference_id", models.CharField(max_length=80, unique=True)),
                ("lock_id", models.CharField(blank=True, max_length=128)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("external_cm", "External Channel Manager"),
                            ("internal_cm", "Internal Channel Manager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=100)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("num_rooms", models.IntegerField(default=1)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("confirmed", "Confirmed"),
                            ("released", "Released"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_lock",
                        to="bookings.booking",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_locks",
                        to="hotels.hotel",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_locks",
                        to="hotels.roomtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
