# Generated by Django 4.2.9 on 2026-01-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('payment_pending', 'Payment Pending'), ('confirmed', 'Confirmed'), ('payment_failed', 'Payment Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('deleted', 'Deleted')], default='reserved', max_length=20),
        ),
    ]
