# Generated by Django 4.2.9 on 2026-01-16 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_wallet_balance_tracking'),
        ('bookings', '0007_booking_confirmed_at_booking_expires_at_and_more'),
    ]

    operations = [
    ]
