# Generated by Django 4.2.9 on 2026-01-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_roommealplan'),
        ('bookings', '0008_merge_20260116_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.roommealplan'),
        ),
        migrations.AlterField(
            model_name='busbookingseat',
            name='passenger_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
