# Generated by Django 4.2.9 on 2026-01-18 11:44

from django.db import migrations


def populate_meal_plans(apps, schema_editor):
    """Populate existing HotelBooking records with default 'room_only' meal plan"""
    HotelBooking = apps.get_model('bookings', 'HotelBooking')
    RoomMealPlan = apps.get_model('hotels', 'RoomMealPlan')
    
    # Find all HotelBooking records with null meal_plan
    null_bookings = HotelBooking.objects.filter(meal_plan__isnull=True)
    
    if not null_bookings.exists():
        return  # Nothing to do
    
    updated_count = 0
    for booking in null_bookings:
        # Get the room type's "Room Only" plan
        room_only_plan = RoomMealPlan.objects.filter(
            room_type=booking.room_type,
            plan_type='room_only',
            is_active=True
        ).first()
        
        if room_only_plan:
            booking.meal_plan = room_only_plan
            booking.save(update_fields=['meal_plan'])
            updated_count += 1
    
    print(f"Populated {updated_count} HotelBooking records with room_only meal plans")


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_hotelbooking_meal_plan_and_more'),
        ('hotels', '0011_roommealplan'),
    ]

    operations = [
        migrations.RunPython(populate_meal_plans),
    ]
