# Generated by Django 4.2.9 on 2026-01-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_populate_meal_plans'),
        ('hotels', '0011_roommealplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.roommealplan'),
        ),
    ]
