# Generated by Django 4.2.9 on 2026-01-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_corporateaccount'),
        ('bookings', '0012_add_completed_at_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_with_promo', to='core.promocode'),
        ),
    ]
