# Generated by Django 4.2.9 on 2026-01-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_make_meal_plan_optional'),
        ('bookings', '0014_hotelbooking_policy_snapshot'),
    ]

    operations = [
    ]
