# Generated by Django 4.2.9 on 2026-01-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_merge_20260121_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone at booking time', max_length=20),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='departure_time_snapshot',
            field=models.CharField(blank=True, help_text='Departure time at booking time', max_length=20),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='operator_name',
            field=models.CharField(blank=True, help_text='Operator name at booking time', max_length=200),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='route_name',
            field=models.CharField(blank=True, help_text='Route description at booking time', max_length=200),
        ),
    ]
