# Generated by Django 4.2.9 on 2026-01-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_busbooking_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='bus_name',
            field=models.CharField(blank=True, help_text='Bus number/name at booking time', max_length=100),
        ),
    ]
