# Generated by Django 4.2.9 on 2026-01-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='price_snapshot',
            field=models.JSONField(blank=True, help_text='Frozen pricing breakdown at booking time', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room_snapshot',
            field=models.JSONField(blank=True, help_text='Frozen room specifications at booking time', null=True),
        ),
    ]
