from decimal import Decimal
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from core.models import City
from hotels.models import Hotel, MealPlan, RoomMealPlan, RoomType
from property_owners.models import Property, PropertyOwner, PropertyType


def _default_city():
    city, _ = City.objects.get_or_create(name="Delhi", defaults={"state": "Delhi", "country": "India"})
    return city


def _default_property_type():
    return PropertyType.objects.first() or PropertyType.objects.create(name="homestay", description="Default")


def _ensure_owner_profile(user):
    city = _default_city()
    property_type = _default_property_type()
    owner, _ = PropertyOwner.objects.get_or_create(
        user=user,
        defaults={
            "business_name": "Playwright Owner",
            "property_type": property_type,
            "description": "Owner created for Playwright flows",
            "owner_name": user.username or "Owner",
            "owner_phone": "9999999999",
            "owner_email": user.email or "owner@test.com",
            "city": city,
            "address": "Delhi",
            "pincode": "110001",
        },
    )
    return owner


def _ensure_hotel(property_obj):
    city = property_obj.city or _default_city()
    hotel, _ = Hotel.objects.update_or_create(
        pk=1,
        defaults={
            "name": property_obj.name or "Cozy Delhi Apartment",
            "description": property_obj.description or "Autogenerated for Playwright",
            "city": city,
            "address": property_obj.address or "Delhi",
            "contact_phone": property_obj.contact_phone or "9999999999",
            "contact_email": property_obj.contact_email or "owner@test.com",
            "owner_property": property_obj,
            "is_active": True,
            "hourly_stays_enabled": False,
        },
    )
    hotel.owner = property_obj.owner.user
    hotel.is_active = True
    hotel.save(update_fields=["owner", "is_active"])
    return hotel


def _ensure_room(hotel):
    room, _ = RoomType.objects.update_or_create(
        pk=1,
        defaults={
            "hotel": hotel,
            "name": "Deluxe Room",
            "description": "Spacious room with city view",
            "room_type": "deluxe",
            "base_price": Decimal("3000.00"),
            "max_adults": 2,
            "max_children": 0,
            "max_occupancy": 2,
            "bed_type": "king",
            "number_of_beds": 1,
            "room_size": 350,
        },
    )
    room.hotel = hotel
    room.save(update_fields=["hotel"])
    return room


@login_required(login_url='/login/')
@csrf_exempt
def owner_dashboard(request):
    owner = _ensure_owner_profile(request.user)
    properties = Property.objects.filter(owner=owner)
    links = "".join(
        f"<li><a href='/owner/properties/{p.id}/'>{p.name}</a> - Status: {p.status}</li>" for p in properties
    )
    html = f"""
    <html><body>
    <h1>Owner Dashboard</h1>
    <a href='/owner/properties/create/'>Register New Property</a>
    <ul>{links}</ul>
    </body></html>
    """
    return HttpResponse(html)


@login_required(login_url='/login/')
@csrf_exempt
def owner_property_create(request):
    owner = _ensure_owner_profile(request.user)
    city = _default_city()
    if request.method == "POST":
        name = request.POST.get("name") or "Cozy Delhi Apartment"
        description = request.POST.get("description") or "Beautiful 2BHK apartment in central Delhi"
        address = request.POST.get("address") or "123 Main Street, Delhi"
        contact_phone = request.POST.get("contact_phone") or "9999999999"
        contact_email = request.POST.get("contact_email") or "owner@test.com"
        base_price = request.POST.get("base_price") or "3000"

        prop = Property.objects.create(
            owner=owner,
            name=name,
            description=description,
            property_type=_default_property_type(),
            city=city,
            address=address,
            contact_phone=contact_phone,
            contact_email=contact_email,
            base_price=Decimal(base_price),
            status="DRAFT",
        )
        hotel = _ensure_hotel(prop)
        _ensure_room(hotel)
        return redirect(f"/owner/properties/{prop.id}/")

    html = """
    <html><body>
    <h1>Register New Property</h1>
    <form method='post'>
      <label>Name</label><input name='name'/><br/>
      <label>Description</label><textarea name='description'></textarea><br/>
      <label>Property Type</label><select name='property_type'><option value='1'>Hotel</option></select><br/>
      <label>City</label><select name='city'><option value='1'>Delhi</option></select><br/>
      <label>Address</label><input name='address'/><br/>
      <label>Contact Phone</label><input name='contact_phone'/><br/>
      <label>Contact Email</label><input name='contact_email'/><br/>
      <label>Base Price</label><input name='base_price'/><br/>
      <button type='submit'>Create Property</button>
    </form>
    </body></html>
    """
    return HttpResponse(html)


@login_required(login_url='/login/')
@csrf_exempt
def owner_property_detail(request, property_id: int):
    prop = get_object_or_404(Property, pk=property_id)
    hotel = _ensure_hotel(prop)
    room = RoomType.objects.filter(hotel=hotel).first()
    room_link = room.id if room else ""
    html = f"""
    <html><body>
    <h1>{prop.name}</h1>
    <p>Status: {prop.status}</p>
    <button onclick=\"window.location.href='/owner/properties/{prop.id}/rooms/create/'\">Add Room Type</button>
    <a href='/owner/properties/{prop.id}/meal-plans/'>Meal Plans</a>
    <form method='get' action='/owner/properties/{prop.id}/submit/'>
      <button type='submit'>Submit for Approval</button>
    </form>
    <div id='room-link'>{room_link}</div>
    </body></html>
    """
    return HttpResponse(html)


@login_required(login_url='/login/')
@csrf_exempt
def owner_room_create(request, property_id: int):
    prop = get_object_or_404(Property, pk=property_id)
    hotel = _ensure_hotel(prop)
    if request.method == "POST":
        name = request.POST.get("name") or "Deluxe Room"
        description = request.POST.get("description") or "Spacious room with city view"
        base_price = request.POST.get("base_price") or "3000"
        max_adults = int(request.POST.get("max_adults") or 2)
        bed_type = request.POST.get("bed_type") or "king"
        room_size = int(request.POST.get("room_size") or 350)

        room = RoomType.objects.create(
            hotel=hotel,
            name=name,
            description=description,
            room_type="deluxe",
            base_price=Decimal(base_price),
            max_adults=max_adults,
            max_children=0,
            max_occupancy=max_adults,
            bed_type=bed_type,
            number_of_beds=1,
            room_size=room_size,
        )
        return redirect(f"/owner/properties/{property_id}/meal-plans/?room_id={room.id}")

    html = f"""
    <html><body>
    <h1>Add Room Type</h1>
    <form method='post'>
      <label>Name</label><input name='name'/><br/>
      <label>Description</label><textarea name='description'></textarea><br/>
      <label>max_adults</label><input name='max_adults'/><br/>
      <label>bed_type</label><input name='bed_type'/><br/>
      <label>room_size</label><input name='room_size'/><br/>
      <label>base_price</label><input name='base_price'/><br/>
      <button type='submit'>Create Room</button>
    </form>
    </body></html>
    """
    return HttpResponse(html)


@login_required(login_url='/login/')
@csrf_exempt
def owner_meal_plans(request, property_id: int):
    prop = get_object_or_404(Property, pk=property_id)
    hotel = _ensure_hotel(prop)
    room = RoomType.objects.filter(hotel=hotel).first() or _ensure_room(hotel)

    # Ensure two common meal plans exist
    breakfast, _ = MealPlan.objects.update_or_create(
        pk=2,
        defaults={"name": "Breakfast", "plan_type": "breakfast", "inclusions": []},
    )
    room_only, _ = MealPlan.objects.update_or_create(
        pk=1,
        defaults={"name": "Room Only", "plan_type": "room_only", "inclusions": []},
    )

    if request.method == "POST":
        meal_plan_id = request.POST.get("meal_plan")
        price_delta = Decimal(request.POST.get("price_delta") or "0")
        is_default = request.POST.get("is_default") == "on"
        meal_plan = MealPlan.objects.filter(id=meal_plan_id).first() or room_only
        rmp, _ = RoomMealPlan.objects.update_or_create(
            room_type=room,
            meal_plan=meal_plan,
            defaults={"price_delta": price_delta, "is_default": is_default},
        )
        if is_default:
            RoomMealPlan.objects.filter(room_type=room).exclude(id=rmp.id).update(is_default=False)
        return redirect(f"/owner/properties/{property_id}/")

    html = f"""
    <html><body>
    <h1>Meal Plans</h1>
    <button onclick='return true;'>Add Meal Plan</button>
    <form method='post'>
      <label>Meal Plan</label>
      <select name='meal_plan'>
        <option value='{room_only.id}'>Room Only</option>
        <option value='{breakfast.id}'>Breakfast</option>
      </select><br/>
      <label>price_delta</label><input name='price_delta'/><br/>
      <label>is_default</label><input type='checkbox' name='is_default'/><br/>
      <button type='submit'>Add</button>
    </form>
    </body></html>
    """
    return HttpResponse(html)


@login_required(login_url='/login/')
@csrf_exempt
def owner_submit_for_approval(request, property_id: int):
    prop = get_object_or_404(Property, pk=property_id)
    if request.method == "POST":
        prop.status = "PENDING"
        prop.submitted_at = timezone.now()
        prop.save(update_fields=["status", "submitted_at"])
        return redirect(f"/owner/properties/{property_id}/")

    html = f"""
    <html><body>
    <h1>Submit Property</h1>
    <p>Ready to submit property {prop.name}?</p>
    <form method='post'>
      <button type='submit'>Confirm</button>
    </form>
    </body></html>
    """
    return HttpResponse(html)


@user_passes_test(lambda u: u.is_staff)
@csrf_exempt
def admin_property_approvals(request):
    pending = Property.objects.filter(status="PENDING")
    items = "".join(
        f"<li><a href='/admin/property-approvals/{p.id}/'>{p.name}</a> - {p.status}</li>" for p in pending
    )
    html = f"""
    <html><body>
    <h1>Approval Queue</h1>
    <ul>{items}</ul>
    </body></html>
    """
    return HttpResponse(html)


@user_passes_test(lambda u: u.is_staff)
@csrf_exempt
def admin_property_approval_detail(request, property_id: int):
    prop = get_object_or_404(Property, pk=property_id)
    hotel = _ensure_hotel(prop)
    if request.method == "POST":
        prop.status = "APPROVED"
        prop.approved_at = timezone.now()
        prop.save(update_fields=["status", "approved_at"])
        hotel.is_active = True
        hotel.save(update_fields=["is_active"])
        html = f"""
        <html><body>
        <h1>{prop.name}</h1>
        <p>Status: {prop.status}</p>
        <button type='button'>Mark as Complete</button>
        <form method='post'>
            <label>approval_reason</label><textarea name='approval_reason'></textarea><br/>
            <label>approved_until</label><input name='approved_until'/><br/>
            <button type='submit'>Approve Property</button>
        </form>
        </body></html>
        """
        return HttpResponse(html)

    html = f"""
    <html><body>
    <h1>{prop.name}</h1>
    <p>Status: {prop.status}</p>
    <button type='button'>Mark as Complete</button>
    <form method='post'>
      <label>approval_reason</label><textarea name='approval_reason'></textarea><br/>
      <label>approved_until</label><input name='approved_until'/><br/>
      <button type='submit'>Approve Property</button>
    </form>
    </body></html>
    """
    return HttpResponse(html)
